import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  digital: [                                     // digital is the name of the sidebar
    'introduction',                             // this is the first .mdx on top
    {                                          // open bracket to create a category to regroup some .mdx docs inside it
      type: 'category',
      label: 'Category 1',
      link: {
        type: 'generated-index',
      },
      collapsed: true,                         // this is to mark that the category is collapsed when accessing the sidebar
      items: [                                //item looks like it is like link to internal document, in here it is at root of /docs
        'doc1',                                
        'doc2',
        'doc3',
        'doc4',
      ],
    },
    {
      type: 'category',                                 // Category: creates a dropdown of sidebar items
      label: 'Category 2',                             // label of this category
      link: {                                         // Link: link to any internal or external page
        type: 'generated-index',                     // Docusaurus can create a sidebar automatically from your filesystem structure: each folder creates a sidebar category, and each file creates a doc link.
        title: 'Label2 H1',                         // Need to try out where it is showing
        description:                               // It's like the _category_.json but in the sidebar.ts
          "Let's go to label 2",                  // add description here
        keywords: ['sidebar'],                   // keyword here for metadata (need to check)
        image: '/img/docusaurus.png',           // image for metadata (need to check)
      },                                       // closing category type
      items: [                                                             // Autogenerated item shit
        'subdocs/subdocs-introduction',                                   // this is the first doc wraped in the beautiful above category
        {                                                                // Open bracket : we open one more thing
          type: 'category',                                             // Nested Category: creates a dropdown of sidebar items Inside the previous one
          label: 'Nested category!',                                   // Intiuitive : label will be shown in the sidebar
          link: {                                                     // Open bracket Link: link to any internal or external page
            type: 'doc',                                             // doc instead of autogenerated?
            id: 'subdocs/introduction',                             // ID : refering of the ID of the front-matter
          },                                                       // Closing the bracket
          items: [
            'guides/docs/create-doc',                                        // new command inside the previous one, item goes under the previous one in same sidebar
            {                                                               // open bracket with new
              type: 'category',                                            // category which is
              label: 'Sidebar',                                           // first the label of the sidebar
              link: {                                                    // we have a link in here open bracket
                type: 'doc',                                            // they say it's doc type
                id: 'guides/docs/sidebar/index',                       // best practice looks like we work with ID in front matter 
              },                                                      // end of category specs
              items: [                                                             // one more nested item found using path
                'guides/docs/sidebar/items',                                      // same
                'guides/docs/sidebar/autogenerated',                             // same
                'guides/docs/sidebar/multiple-sidebars',                        // same
              ],                                                               // closing bracket
            },                                                                // closing category from doc links
            'guides/docs/versioning',                                                    // one more doc from it's  docs/guides/docs/versioning.mdx
            'guides/docs/multi-instance',                                               // same
          ],
        },
        'blog',
        {
          type: 'category',
          label: 'Markdown Features',
          link: {
            type: 'doc',                                          //  Doc: link to a doc page, associating it with the sidebar
            id: 'guides/markdown-features/introduction',
          },
          items: [
            'guides/markdown-features/react',
            'guides/markdown-features/tabs',
            'guides/markdown-features/code-blocks',
            'guides/markdown-features/admonitions',
            'guides/markdown-features/toc',
            'guides/markdown-features/assets',
            'guides/markdown-features/links',
            'guides/markdown-features/plugins',
            'guides/markdown-features/math-equations',
            'guides/markdown-features/diagrams',
            'guides/markdown-features/head-metadata',
          ],
        },
        'styling-layout',
        'swizzling',
        'static-assets',
        'search',
        'browser-support',
        'seo',
        'using-plugins',
        'deployment',
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'i18n/introduction'},
          items: [
            {
              type: 'doc',
              id: 'i18n/tutorial',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'i18n/git',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'i18n/crowdin',
              label: 'Using Crowdin',
            },
          ],
        },
        'guides/whats-next',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'advanced/index'},
      items: [
        'advanced/architecture',
        'advanced/plugins',
        'advanced/routing',
        'advanced/ssg',
        'advanced/client',
      ],
    },
    {
      type: 'category',
      label: 'Upgrading',
      link: {
        type: 'doc',
        id: 'migration/index',
      },
      items: [
        'migration/v3',
        // TODO do we want to keep upgrade docs for older Docusaurus versions?
        // It contains links to docs of current version :/
        {
          type: 'category',
          label: 'To Docusaurus v2',
          items: [
            'migration/v2/migration-overview',
            'migration/v2/migration-automated',
            'migration/v2/migration-manual',
            'migration/v2/migration-versioned-sites',
            'migration/v2/migration-translated-sites',
          ],
        },
      ],
    },
  ],
  api: [
    'cli',
    'docusaurus-core',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;