import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebar1: [                                     // sidebar1 is the name of the sidebar
    'doc1',                             // this is the first .mdx on top
    {                                // open bracket to create a category to regroup some .mdx docs inside it
      type: 'category',
      label: 'Docs2',
      link: {
        type: 'generated-index',          // generated by the docu plugin - means no doc2
      },
      collapsed: false,                         // this is to mark that the category is not collabsed as there is no doc2
      items: [                                //item looks like it is like links to internal document, in here it is at root of /docs
        'docs2/doc2-1',                                // I added them to a folder as this is a template and it's more streamlined like that
        'docs2/doc2-2',
        'docs2/doc2-3',
        'docs2/doc2-4',
      ],
    },
    {
      type: 'category',                  // Category: creates a dropdown category with items
      label: 'Docs3',                             // label of this category - no doc3 as it is a generated index and title/descripion/keyword/image in the sidebars.ts
      link: {                                         // Link: link to any internal or external page
        type: 'generated-index',                     // Docusaurus can create a sidebar automatically from your filesystem structure: each folder creates a sidebar category, and each file creates a doc link.
        title: 'Docs3 H1',                         // Need to try out where it is showing
        description:                               // It's like the _category_.json but in the sidebar.ts
          "Docs3 body",                  // add description here
        keywords: ['sidebar'],                   // keyword here for metadata (need to check)
        image: '/img/docusaurus.png',           // image for metadata (need to check)
      },                                       // closing category type
      items: [                                                             // New item which wiil be
        'docs3/doc3-1',                                   // a link to a subfolder and a .mdx file path
        {                                                                // Open bracket : we open one more thing
          type: 'category',                                             // Nested Category: creates a dropdown of sidebar items Inside the previous one
          label: 'Docs3-2 ',                                   // Intiuitive : label will be shown in the sidebar
          link: {                                                     // Open bracket Link: link to any internal or external page
            type: 'doc',                                             // doc instead of autogenerated?
            id: 'docs3/doc32',                             // ID : refering of the ID of the front-matter
          },                                                       // Closing the bracket
          items: [
            'docs3/docs3-2/doc3-2-1',                        // nested twice by adding one more level
            {                                                               // open bracket with new
              type: 'category',                                            // category which is
              label: 'Docs3-2-2',                                           // first the label of the sidebar
              link: {                                                    // we have a link in here open bracket
                type: 'doc',                                            // they say it's doc type
                id: 'docs3/docs3-2/doc322',                       // index page for the category in a .mdx doc file (instead of .json)
              },                                                      // end of category specs
              items: [                                                             // one more nested item found using path
                'docs3/docs3-2/docs3-2-2/doc3-2-2-1',                                      // same with slug
                'docs3/docs3-2/docs3-2-2/doc3-2-2-2',                             // same with slug
                'docs3/docs3-2/docs3-2-2/doc3-2-2-3',                        // same with slug
              ],                                                               // closing bracket
            },                                                                // closing category from doc links
            'docs3/docs3-2/doc3-2-3',                                                    // one more doc from it's  docs/guides/docs/versioning.mdx
            'docs3/docs3-2/doc3-2-4',                                               // same
          ],                                                               // Closing the item
        },                                                                //  Closing the subdoc
        'docs3/doc3-3',                     // link to docs/docs3/doc3-4.mdx - most simple thing to do inside the current sidebar
        {
          type: 'category',                                                       // New nested - subdocs - subdocs3
          label: 'Docs3-4',
          link: {
            type: 'doc',                                          //  Doc: link to a doc page, associating it with the sidebar
            id: 'docs3/doc34',                         // path to introduction subdocs3 using path and ID at the end of the path
          },
          items: [                                                         // multipurpose items: SidebarCategoriesShorthand | SidebarItemConfig[]
            'docs3/docs3-5/doc3-4-1',                              // link to doc to be added to the nested category 3 from subdocs/subdocs3/ID
            'docs3/docs3-5/doc3-4-2',
            'docs3/docs3-5/doc3-4-3',
            'docs3/docs3-5/doc3-4-4',
            'docs3/docs3-5/doc3-4-5',
            'docs3/docs3-5/doc3-4-6',
            'docs3/docs3-5/doc3-4-7',
            'docs3/docs3-5/doc3-4-8',
            'docs3/docs3-5/doc3-4-9',
            'docs3/docs3-5/doc3-4-10',
            'docs3/docs3-5/doc3-4-11',
          ],
        },
        'styling-layout',
        'swizzling',
        'static-assets',
        'search',
        'browser-support',
        'seo',
        'using-plugins',
        'deployment',
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'i18n/introduction'},
          items: [
            {
              type: 'doc',
              id: 'i18n/tutorial',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'i18n/git',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'i18n/crowdin',
              label: 'Using Crowdin',
            },
          ],
        },
        'guides/whats-next',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'advanced/index'},
      items: [
        'advanced/architecture',
        'advanced/plugins',
        'advanced/routing',
        'advanced/ssg',
        'advanced/client',
      ],
    },
    {
      type: 'category',
      label: 'Upgrading',
      link: {
        type: 'doc',
        id: 'migration/index',
      },
      items: [
        'migration/v3',
        // TODO do we want to keep upgrade docs for older Docusaurus versions?
        // It contains links to docs of current version :/
        {
          type: 'category',
          label: 'To Docusaurus v2',
          items: [
            'migration/v2/migration-overview',
            'migration/v2/migration-automated',
            'migration/v2/migration-manual',
            'migration/v2/migration-versioned-sites',
            'migration/v2/migration-translated-sites',
          ],
        },
      ],
    },
  ],
  api: [
    'cli',
    'docusaurus-core',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;